<?php

define('DATEX_USE_INTL', class_exists('IntlDateFormatter'));

require_once 'src/DatexInterface.php';
require_once 'src/DatexPartialImplementation.php';
require_once 'src/DatexIntlCalendar.php';
require_once 'src/DatexPersianIntlCalendar.php';
require_once 'datex_date.inc';

/**
 * Implements hook_menu().
 *
 * For admin forms.
 */
function datex_menu() {
  $items['admin/config/regional/date-time/datex'] = [
    'title' => 'Datex',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['datex_admin_form'],
    'access arguments' => ['administer site configuration'],
    'type' => MENU_LOCAL_TASK,
    'file' => 'datex.admin.inc',
  ];
  $items['admin/config/regional/date-time/datex/edit/%'] = [
    'title' => 'Datex edit schema',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['datex_schema_edit_form', 6],
    'access arguments' => ['administer site configuration'],
    'type' => MENU_CALLBACK,
    'file' => 'datex.admin.inc',
  ];
  return $items;
}

/**
 * Implementation of hook_views_api().
 */
function datex_views_api() {
  return [
    'api' => 3,
    'path' => drupal_get_path('module', 'datex'),
  ];
}

/**
 * Implements hook_views_data_alter().
 */
function datex_views_data_alter(&$data) {
  foreach ($data as $key => &$value) {
    if (is_array($value)) {
      datex_views_data_alter($value);
    }

    if ($value === 'date_views_argument_handler_simple') {
      $value = '_datex_date_views_argument_handler_simple';
    }

    // Field Formatter --------------------------------------------------------
    $change = [
      'year',
      'month',
      'day',
      'fulldate',
      'year_month',
      'week',
    ];
    $change = [
      'views_handler_field_date',
      'views_handler_field_last_comment_timestamp',
      'views_handler_field_history_user_timestamp',
      'views_handler_field_ncs_last_updated',
      //      'views_handler_filter_date',
      //      'views_handler_filter_ncs_last_updated',
      //      'views_handler_filter_history_user_timestamp',
    ];
    if (in_array($value, $change, TRUE)) {
      $value = '_datex_' . $value;
    }

    // Contextual filters -----------------------------------------------------
    $change = [
      'year',
      //        'month',
      //        'day',
      'fulldate',
      'year_month',
      //        'week',
    ];
    foreach ([
               'views_handler_argument_node_created_',
               'views_handler_argument_node_changed_',
             ] as $item) {
      foreach ($change as $g) {
        if ($value === $item . $g) {
          $value = '_datex_' . $value;
        }
      }
    }
  }
}

function datex_enable() {
  if (DATEX_USE_INTL) {
    return;
  }
  require_once 'datex.install';
  $err = datex_requirements();
  drupal_set_message(t('warning') . '!!! ' . $err['description'], 'warning');
}

// ___________________________________________________________________ INTERNAL

/**
 * Calendars supported by PHP-Intl.
 */
function _datex_available_calendars() {
  return [
    'japanese' => t('Japanese'),
    'buddhist' => t('Buddhist'),
    'chinese' => t('Chinese'),
    'persian' => t('Persian'),
    'indian' => t('Indian'),
    'islamic' => t('Islamic'),
    'hebrew' => t('Hebrew'),
    'coptic' => t('Coptic'),
    'ethiopic' => t('Ethiopic'),
  ];
}

/**
 * Get calendar for a/current language from schema.
 *
 * @param string $for_schema
 * @param null $for_lang
 *
 * @return null
 */
function _datex_language_calendar($for_schema = 'default', $for_lang = NULL) {
  if (!$for_lang) {
    $for_lang = $GLOBALS['language']->language;
  }
  $cfg = variable_get('datex_schema', []);
  return !isset($cfg[$for_schema][$for_lang])
    ? NULL
    : $cfg[$for_schema][$for_lang];
}

function _datex_schema_form_options() {
  return [
      'disabled' => t('Disabled'),
      'default' => t('Default'),
    ] + drupal_map_assoc(array_keys(variable_get('datex_schema', [])));
}

function datex_factory($tz = NULL, $calendar = NULL, $lang_code = NULL) {
  if (!$calendar) {
    $calendar = _datex_language_calendar();
  }
  if (!$calendar) {
    return NULL;
  }
  if (!$lang_code) {
    if (count(language_list()) === 1) {
      $lang_code = 'fa';
    }
    else {
      $lang_code = $GLOBALS['language']->language;
    }
  }
  if (!DATEX_USE_INTL) {
    switch ($calendar) {
      case 'persian':
        require_once 'src/DatexPoorMansJaliliCalendar.php';
        return new DatexPoorMansJaliliCalendar(is_string($tz) ? timezone_open($tz) : $tz, $lang_code);
      default:
        return NULL;
    }
  }

  switch ($calendar) {
    case 'persian':
      return new DatexPersianIntlCalendar($tz, $calendar, $lang_code);
    default:
      return new DatexIntlCalendar($tz, $calendar, $lang_code);
  }
}

// _______________________________________________________________________ MAIN

/**
 * Implements hook_preprocess_node().
 *
 * Localizes 'published on' date.
 *
 * @param $variables
 */
function datex_preprocess_node(&$variables) {
  $calendar = datex_factory();
  if (!$calendar) {
    return;
  }
  $calendar->setTimestamp($variables['created']);

  $format = variable_get('date_format_medium', 'D, m/d/Y - H:i');
  $variables['date'] = $calendar->format($format);
  if (isset($variables['display_submitted'])) {
    $variables['submitted'] = t('Submitted by !username on !datetime', [
      '!username' => $variables['name'],
      '!datetime' => $variables['date'],
    ]);
  }
}

/**
 * Implements hook_preprocess_comment().
 *
 * Localizes 'published on' date.
 *
 * @param $variables
 */
function datex_preprocess_comment(&$variables) {
  $calendar = datex_factory();
  if (!$calendar) {
    return;
  }

  $calendar->setTimestamp($variables['elements']['#comment']->created);

  // Timestamp set while calling factory.
  $fmt = variable_get('date_format_medium', '');
  $variables['changed'] = $calendar->format($fmt);
  $calendar->setTimestamp($variables['elements']['#comment']->created);
  $variables['created'] = $calendar->format($fmt);
  $variables['submitted'] = t('Submitted by !username on !datetime', [
    '!username' => $variables['author'],
    '!datetime' => $variables['created'],
  ]);
}

function _datex_comment_edit_form_date_validate($f, &$fs) {
  $calendar = datex_factory();
  if (!$calendar) {
    return;
  }

  if (!isset($fs['values']['date'])) {
    return;
  }

  $date = &$fs['values']['date'];

  $m = [];
  $pattern = '#^([0-9]{2,4})[-\/\\\]([0-9]{1,2})[-\/\\\]([0-9]{1,2})( {1,}([0-9]{1,2})\:([0-9]{1,2}))?#';
  $ok = preg_match($pattern, $date, $m);
  if ($ok && count($m) == 7) {
    $calendar->setDateLocale($m[1], $m[2], $m[3]);
    $calendar->setTime($m[5], $m[6], 0);
    $date = $calendar->xFormat('Y-m-d H:i:s O');
  }
  else {
    form_set_error('date', t('Invalid date'));
  }
}

function _datex_node_edit_form_date_validate($el, &$fs, $f) {
  if (!$fs['#datexified'] || empty($el['#value'])) {
    return;
  }

  $calendar = datex_factory();
  if (!$calendar) {
    form_set_error($el['#name'], t('Invalid site language.'));
  }

  $m = [];
  $pattern = '#^([0-9]{2,4})[-\/\\\]([0-9]{1,2})[-\/\\\]([0-9]{1,2})( {1,}([0-9]{1,2})\:([0-9]{1,2})\:([0-9]{1,2}))?#';
  $ok = preg_match($pattern, $el['#value'], $m);
  if ($ok && count($m) == 8) {
    $calendar->setDateLocale($m[1], $m[2], $m[3]);
    $calendar->setTime($m[5], $m[6], $m[7]);
    $el['#value'] = $calendar->xFormat('Y-m-d H:i:s O');
    form_set_value($el, $el['#value'], $fs);
  }
  else {
    form_set_error($el['#name'], t('You have to specify a valid date.'));
  }
}

/**
 * Implements hook_form_alter().
 *
 * Modules to support:
 *  - Scheduler
 *  - translation date
 *  - views exposed forms
 *
 * @param $f
 * @param $fs
 * @param $form_id
 */
function datex_form_alter(&$f, &$fs, $form_id) {
  if ($form_id === 'node_admin_content' && isset($f['admin']['nodes']['#options'])) {
    // Contents list (/admin/content/).
    $calendar = datex_factory();
    if (!$calendar) {
      return;
    }
    $format = variable_get('date_format_short', '');
    if (!$format) {
      return;
    }
    foreach ($f['admin']['nodes']['#options'] as &$node) {
      $date = &$node['changed'];
      $date_obj = date_create_from_format($format, $date);
      $calendar->setTimestamp($date_obj->format('U'));
      $date = $calendar->format($format);
    }
    return;
  }

  $calendar = datex_factory(NULL, NULL, 'en');
  if (!$calendar) {
    return;
  }
  if (isset($f['#node_edit_form'])) {
    $fs['#datexified'] = TRUE;
    $now = $calendar->format('o-m-d H:i:s O');
    if (isset($f['author']['date'])) {
      $t_args = ['%date' => $now];
      $f['author']['date']['#description'] = t(
        'Format: %date The date format is YYYY-MM-DD and time is H:i:s. Leave blank to use the time of form submission.', $t_args);
      $f['author']['date']['#element_validate'][] = '_datex_node_edit_form_date_validate';
    }
    if (isset($f['scheduler_settings']) && !module_exists('date_popup')) {
      foreach (['publish_on', 'unpublish_on'] as $name) {
        if (isset($f['scheduler_settings'][$name])) {
          $f['scheduler_settings'][$name]['#element_validate'][] = '_datex_node_edit_form_date_validate';
        }
        if (isset($f['#node']->scheduler[$name]) && !empty($f['scheduler_settings'][$name]['#default_value'])) {
          $calendar->setTimestamp($f['#node']->scheduler[$name]);
          $f['scheduler_settings'][$name]['#default_value']
            = $calendar->format('Y-m-d H:i:s O');
        }
        $f['scheduler_settings'][$name]['#description'] = t('Format: %date The date format is YYYY-MM-DD and time is H:i:s. Leave blank to disable scheduled.', ['%date' => $now]);
      }
    }
    if (!empty($f['author']['date']['#default_value'])) {
      $calendar->setTimestamp($f['created']['#value']);
      $f['author']['date']['#default_value'] = $calendar->format('Y-m-d H:i:s O');
    }
  }
  elseif (isset($f['#id']) && $f['#id'] === 'comment-form' && $f['#entity'] && $f['#entity']->cid) {
    if (!isset($f['#validate'])) {
      $f['#validate'] = [];
    }
    if (isset($f['author']['date'])) {
      $fmt = 'Y-m-d H:i O';
      $date_obj = date_create_from_format($fmt, $f['author']['date']['#default_value']);
      $calendar->setTimestamp($date_obj->format('U'));
      $f['author']['date']['#default_value'] = $calendar->format($fmt);
    }
    array_unshift($f['#validate'], '_datex_comment_edit_form_date_validate');
  }
}
