<?php

define('DATEX_USE_INTL', FALSE && class_exists('IntlDateFormatter'));

use \Drupal\datex\Datex\DatexPoorMansJaliliCalendar;
use \Drupal\datex\Datex\DatexPoorMansGregorianCalendar;
use \Drupal\datex\Datex\DatexPersianIntlCalendar;
use \Drupal\datex\Datex\DatexIntlCalendar;

function datex_factory($tz = NULL, $lang_code = '', $calendar_name = '') {
  // COPY FROM common.inc::format_date() (drupal 7).
  static $drupal_static_fast;
  if (!isset($drupal_static_fast)) {
    $drupal_static_fast['timezones'] = [];
  }
  $timezones = &$drupal_static_fast['timezones'];

  if (!$tz) {
    $tz = drupal_get_user_timezone();
  }
  if (is_string($tz)) {
    if (!isset($timezones[$tz])) {
      $timezones[$tz] = timezone_open($tz);
    }
    $tz = $timezones[$tz];
  }

  if (!$calendar_name) {
    $for_lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $for_schema = 'default';
    $cfg = \Drupal::config('datex.schemas')->get($for_schema);
    $calendar_name = is_array($cfg) && isset($cfg[$for_lang]) ? $cfg[$for_lang] : NULL;
    if (count(\Drupal::languageManager()->getLanguages()) === 1) {
      $calendar_name = 'persian';
    }
  }
  if (!$calendar_name) {
    return NULL;
  }

  if (!$lang_code) {
    if (count(\Drupal::languageManager()->getLanguages()) === 1) {
      $lang_code = 'fa';
    }
    else {
      $lang_code = \Drupal::languageManager()->getCurrentLanguage()->getId();
    }
  }

  if (!DATEX_USE_INTL) {
    switch ($calendar_name) {
      case 'persian':
        return new DatexPoorMansJaliliCalendar(is_string($tz) ? timezone_open($tz) : $tz, $lang_code);
      default:
        return new DatexPoorMansGregorianCalendar(is_string($tz) ? timezone_open($tz) : $tz, $lang_code);
    }
  }
  switch ($calendar_name) {
    case 'persian':
      return new DatexPersianIntlCalendar($tz, $calendar_name, $lang_code);
    default:
      return new DatexIntlCalendar($tz, $calendar_name, $lang_code);
  }
}

/**
 * Calendars supported by PHP-Intl.
 */
function _datex_available_calendars() {
  return [
    'japanese' => t('Japanese'),
    'buddhist' => t('Buddhist'),
    'chinese' => t('Chinese'),
    'persian' => t('Persian'),
    'indian' => t('Indian'),
    'islamic' => t('Islamic'),
    'hebrew' => t('Hebrew'),
    'coptic' => t('Coptic'),
    'ethiopic' => t('Ethiopic'),
  ];
}

/**
 * Implements hook_element_info_alter().
 *
 * Swap drupal elements with datex elements.
 */
function datex_element_info_alter(array &$info) {
  $rep = function ($find_for) {
    switch ($find_for) {
      case \Drupal\Core\Datetime\Element\Datelist::class:
        $rep = \Drupal\datex\Element\DatexDateList::class;
        break;
      case \Drupal\Core\Datetime\Element\Datetime::class:
        $rep = \Drupal\datex\Element\DatexDateTime::class;
        break;
      case \Drupal\Core\Render\Element\Date::class:
        $rep = \Drupal\datex\Element\DatexDate::class;
        break;
      default:
        $rep = NULL;
    }
    return $rep;
  };
  foreach (['date', 'datelist', 'datetime'] as $el_) {
    if (!isset($info[$el_])) {
      continue;
    }
    $el = &$info[$el_];
    if ($el_ === 'date' || $el_ === 'datetime') {
      $el['#attached']['library'][] = 'datex/picker';
    }
    foreach ([
               '#process',
               '#pre_render',
               '#element_validate',
               '#value_callback',
             ] as $attr_) {
      if (!isset($el[$attr_])) {
        continue;
      }
      foreach ($el[$attr_] as $ai => &$a) {
        if (is_array($a)) {
          $a[0] = $rep($a[0]) ?: $a[0];
        }
        else {
          $el[$attr_][$ai] = $rep($a) ?: $a;
        }
      }
    }
  }
}

/**
 * Implements hook_field_widget_info_alter().
 */
function datex_field_widget_info_alter(&$info) {
  $info['datetime_default']['class'] = \Drupal\datex\Plugin\Field\FieldWidget\DatexDateTimeDefaultWidget::class;
  $info['datetime_datelist']['class'] = \Drupal\datex\Plugin\Field\FieldWidget\DatexDateTimeDatelistWidget::class;
  $info['datetime_timestamp']['class'] = \Drupal\datex\Plugin\Field\FieldWidget\DatexTimestampDatetimeWidget::class;
  if (isset($info['datetime_timestamp_no_default'])) {
    $info['datetime_timestamp_no_default']['class'] = \Drupal\datex\Plugin\Field\FieldWidget\DatexTimestampDatetimeNoDefaultWidget::class;
  }
  foreach ([
             'default',
             'datelist',
             'timestamp',
             'datetime_timestamp_no_default',
           ] as $item) {
    $info["datetime_$item"]['provider'] = 'datex';
  }
}
